linux:
	g++ -g -std=c++17 -D LINUX	\
	Matrix.h 					\
	Operations.h				\
	ErrorHandler.h				\
	Matrix.cpp					\
	Adjoint.cpp					\
	Cofactors.cpp				\
	Invert.cpp					\
	Determinant.cpp				\
	ErrorHandler.cpp			\
	MatrixMultiplication.cpp	\
	Minors.cpp					\
	Orthogonalization.cpp		\
	Rank.cpp					\
	REF.cpp						\
	RREF.cpp					\
	Trace.cpp					\
	Main.cpp -o lalib

windows:
	g++ -g -std=c++17 			\
	Matrix.h 					\
	Operations.h				\
	ErrorHandler.h				\
	Matrix.cpp					\
	Adjoint.cpp					\
	Cofactors.cpp				\
	Invert.cpp					\
	Determinant.cpp				\
	ErrorHandler.cpp			\
	MatrixMultiplication.cpp	\
	Minors.cpp					\
	Orthogonalization.cpp		\
	Rank.cpp					\
	REF.cpp						\
	RREF.cpp					\
	Trace.cpp					\
	Main.cpp -o lalib
